[versions]
agp = "8.12.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lottie = "6.6.7"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
mpandroidchart = "v3.1.0"
navigationFragment = "2.9.0"
playServicesAds = "24.4.0"
preference = "1.2.1"
legacySupportV4 = "1.0.0"
recyclerview = "1.4.0"
kotlin = "2.1.0"
coreKtx = "1.16.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version = "1.10.1" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

